export { default } from "./src/aave-protocol-evm.js";
export type TransactionResult = import("@wdk/wallet").TransactionResult;
export type BorrowOptions = import("@wdk/wallet/protocols").BorrowOptions;
export type BorrowResult = import("@wdk/wallet/protocols").BorrowResult;
export type SupplyOptions = import("@wdk/wallet/protocols").SupplyOptions;
export type WithdrawOptions = import("@wdk/wallet/protocols").WithdrawOptions;
export type WithdrawResult = import("@wdk/wallet/protocols").WithdrawResult;
export type RepayOptions = import("@wdk/wallet/protocols").RepayOptions;
export type SupplyResult = import("./src/aave-protocol-evm.js").SupplyResult;
export type RepayResult = import("./src/aave-protocol-evm.js").RepayResult;
export type AccountData = import("./src/aave-protocol-evm.js").AccountData;
